apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-mcp.fullname" . }}-config
  labels:
    {{- include "kube-mcp.labels" . | nindent 4 }}
data:
  config.toml: |
{{ include "kube-mcp.config" . | indent 4 }}

