{{- if and .Values.server.http.oauth.enabled .Values.server.http.oauth.clientSecretFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-mcp.fullname" . }}-oauth-http
  labels:
    {{- include "kube-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.server.http.oauth.clientSecretFromSecret | b64enc }}
{{- end }}

